In [2]:
import yfinance as yf

In [3]:
ticker = yf.Ticker("TSLA")

In [4]:
df = ticker.history(period="max")

if the price the previous 4 days or more is below the 10-day simple moving average for each of those days AND the current price above 10 day simple moving average then buy it now, it will pop sometime the next day

In [41]:
df['ma_10'] = df.Close.rolling(window=10).mean()
df['HighNext'] = df.High.shift(-1)

In [42]:
mask = (df.Close > df.ma_10) & (df.Close.shift(1) < df.ma_10) & (df.Close.shift(2) < df.ma_10) & (df.Close.shift(3) < df.ma_10) & (df.Close.shift(4) < df.ma_10)
condition = df.loc[mask]
condition

,Open,High,Low,Close,Volume,Dividends,Stock Splits,ma_10,CloseNext,HighNext
Date,,,,,,,,,,
2010-07-14,3.588000,4.030000,3.552000,3.968000,20976000,0,0.0,3.735800,3.978000,4.300000
2010-09-28,4.208000,4.298000,4.152000,4.280000,6072500,0,0.0,4.128800,4.396000,4.406000
2010-10-14,4.200000,4.206000,4.080000,4.150000,1474000,0,0.0,4.116000,4.108000,4.180000
2010-12-17,6.268000,6.308000,6.142000,6.272000,4065000,0,0.0,6.173200,6.340000,6.438000
2011-01-06,5.366000,5.600000,5.362000,5.576000,10306000,0,0.0,5.418200,5.648000,5.716000
...,...,...,...,...,...,...,...,...,...,...
2022-01-12,1078.849976,1114.839966,1072.589966,1106.219971,27913000,0,0.0,1088.500989,1031.560059,1115.599976
2022-02-28,815.010010,876.859985,814.710022,870.429993,33002300,0,0.0,852.154999,864.369995,889.880005
2022-05-04,903.940002,955.500000,885.280029,952.619995,27214600,0,0.0,928.286005,873.280029,945.599976
2022-05-26,661.419983,718.669983,653.659973,707.729980,35334400,0,0.0,700.828998,759.630005,759.799988
2022-07-07,701.760010,736.090027,696.630005,733.630005,27310200,0,0.0,704.378998,752.289978,764.940002

In [43]:
wins, losses = sum(condition.HighNext > condition.Close), sum(condition.HighNext < condition.Close)
total = wins + losses
fpct = lambda x: '{:.1%}'.format(x)

wins, fpct(wins / total), losses, fpct(losses / total), total, 1

(99, '93.4%', 7, '6.6%', 106, 1)